### PR TITLE
chore: update sdks

### PR DESCRIPTION
**Pull request by meeh0w**
## Description

Updates SDKs, the new version changes BTC fee estimation:
* `Normal` preset will estimate for tx inclusion within 6 blocks instead of 7
* fee rate is rounded _up_ instead of to the closest integer (e.g. `3.4 -> 4.0` instead of `3.4 -> 3.0`)

## Checklist for the author
- [ ] I've covered new/modified business logic with Jest test cases.
- [x] I've tested the changes myself before sending it to code review and QA.

### CODE REVIEW

**Comment by bferenc** [comment]
Gave it a test and I was constantly getting one of these 2 results 🤔 
image
Screenshot 2024-08-21 at 15 22 17

**Comment by meeh0w** [comment]
@bferenc The first looks like fees from EVM leaking through (a race condition probably, I've suspected it [here](https://ava-labs.atlassian.net/browse/CP-8220) a few months back, but was not able to reproduce).

The 2nd are the proper BTC testnet fees (yup...I know...pretty expensive 😆).

**Review by bferenc — DISMISSED** [review]

**Comment by meeh0w** [comment]
@bferenc I just got this idea and managed to reproduce the 1st one by triggering a BTC send, opening a 2nd extension window and changing the network to C-Chain in it.

I'll file a bug ticket!

**Comment by bferenc** [comment]
> @bferenc I just got this idea and managed to reproduce the 1st one by triggering a BTC send, opening a 2nd extension window and changing the network to C-Chain in it.
> 
> I'll file a bug ticket!

Awesome, thank you!

**Comment by meeh0w** [comment]
Ticket: https://ava-labs.atlassian.net/browse/CP-9098

**Comment by meeh0w** [comment]
@bferenc Can you re-approve? I had to rebase :)

**Review by bferenc — APPROVED** [review]

**Review by gergelylovas — APPROVED** [review]

**Pull request merged**
